name: Deploy to VPS

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Set up Prisma
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        npx prisma generate
        # Skip db push for MongoDB (it's not needed for MongoDB)
        # npx prisma db push --skip-generate
      
    - name: Build project
      run: npm run build
      
    - name: Run tests (if any)
      run: |
        npm run test --if-present
        npm run lint --if-present
      
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /root/devdocsfile
          echo "Pulling latest changes..."
          git pull origin main
          echo "Installing dependencies..."
          npm ci --production
          echo "Generating Prisma client..."
          npx prisma generate
          echo "Running database migrations..."
          npx prisma migrate deploy
          echo "Building project..."
          npm run build
          echo "Restarting application..."
          pm2 restart devdocs-app || pm2 start npm --name "devdocs-app" -- start
          echo "Deployment completed successfully!"
          echo "Current PM2 status:"
          pm2 status
